# Generated by Django 5.2.8 on 2025-11-23 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_mlb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mlb',
            old_name='name',
            new_name='test',
        ),
    ]
